---
# Role tasks

- name: Create temporary unarchive directory
  tempfile:
    state: directory
    suffix: _unarchive
  register: tmp_unarchive_directory

- name: Unarchive a file
  unarchive:
    src: files/sqljdbc_7.4.1.0_esn.tar.gz # TODO
    #      files/sqljdbc_7.4.1_esn.tar.gz
    # src: files/{{ sqlserver_jdbc_connector_archive_name }} # TODO

    dest: "{{ tmp_unarchive_directory.path }}"
  #   list_files: yes
  # register: unarchive_result

- name: Get jar from  unarchived files
  find:
    paths: "{{ tmp_unarchive_directory.path }}"
    patterns: "{{ sqlserver_jdbc_connector_jar_name }}"
    recurse: yes
  register: find_result

- name: Create jdbc connector destination directory
  file:
    path: "{{ sqlserver_jdbc_connector_destination_directory }}"
    state: directory

- name: Copy jdbc connector jar
  vars:
    jar_file: "{{ find_result.files[0].path }}"
  copy:
    src: "{{ jar_file }}"
    remote_src: yes
    dest: "{{ sqlserver_jdbc_connector_destination_directory }}"

- name: Clean temporary directory
  file:
    path: "{{ tmp_unarchive_directory.path }}"
    state: absent
  when: tmp_unarchive_directory.path is defined
