---
# Role install tasks

- block:
    - name: create sqlserver jdbc connector destination directory
      file:
        path: "{{ sqlserver_jdbc_connector_dir }}"
        state: directory

    - name: extract sqlserver jdbc connector artifact
      unarchive:
        src: "{{ sqlserver_jdbc_connector_package }}"
        dest: "{{ sqlserver_jdbc_connector_package | dirname }}"
        copy: no
        creates: "{{ sqlserver_jdbc_connector_jar_path }}"
      register: sqlserver_jdbc_connector_unarchive_result

    - name: install sqlserver jdbc connector
      copy:
        src: >-
          {{ sqlserver_jdbc_connector_unarchive_dir
             + "/"
             + sqlserver_jdbc_connector_jar_filename }}
        dest: "{{ sqlserver_jdbc_connector_dir }}"
        remote_src: yes
  when:
    - sqlserver_jdbc_connector_state == "present"
    - not sqlserver_jdbc_connector_jar_check_result.stat.exists
  tags:
    - role::sqlserver_jdbc_connector
    - role::sqlserver_jdbc_connector::install
