---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:35
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  playbooks:
    cleanup: ../resources/cleanup.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ansible_user: root
          sqlserver_jdbc_connector_state: present
          sqlserver_jdbc_connector_version: 7.4.1.jre8
          sqlserver_jdbc_connector_dir: /root
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
